# Generated by Django 6.0.1 on 2026-01-24 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Karya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_karya', models.CharField(max_length=200)),
                ('pembuat', models.CharField(max_length=200, verbose_name='Nama Pembuat')),
                ('prodi', models.CharField(choices=[('PTIK', 'Pendidikan Teknik Informatika dan Komputer'), ('PTE', 'Pendidikan Teknik Elektro'), ('TE', 'Teknik Elektro'), ('TK', 'Teknik Komputer'), ('MKU', 'Mata Kuliah Umum')], max_length=50)),
                ('deskripsi', models.TextField()),
                ('link_demo', models.URLField(blank=True, null=True, verbose_name='Link Video/Demo')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Review'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Materi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pengupload', models.CharField(max_length=100)),
                ('email', models.EmailField(help_text='Email untuk notifikasi jika materi diterima/ditolak', max_length=254)),
                ('prodi', models.CharField(choices=[('PTIK', 'Pendidikan Teknik Informatika dan Komputer'), ('PTE', 'Pendidikan Teknik Elektro'), ('TE', 'Teknik Elektro'), ('TK', 'Teknik Komputer'), ('MKU', 'Mata Kuliah Umum')], max_length=50)),
                ('semester', models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6'), (7, 'Semester 7'), (8, 'Semester 8')])),
                ('mata_kuliah', models.CharField(max_length=100)),
                ('judul', models.CharField(max_length=200)),
                ('deskripsi', models.TextField(blank=True, null=True)),
                ('link_materi', models.URLField(help_text='Masukkan Link Google Drive (Pastikan akses Public/Anyone with link)')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Review'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=20)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prestasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_mahasiswa', models.TextField(help_text='Pisahkan koma jika tim', verbose_name='Nama Mahasiswa/Tim')),
                ('prodi', models.CharField(choices=[('PTIK', 'Pendidikan Teknik Informatika dan Komputer'), ('PTE', 'Pendidikan Teknik Elektro'), ('TE', 'Teknik Elektro'), ('TK', 'Teknik Komputer'), ('MKU', 'Mata Kuliah Umum')], max_length=50)),
                ('nama_lomba', models.CharField(max_length=200)),
                ('juara', models.CharField(help_text='Contoh: Juara 1, Gold Medal', max_length=100)),
                ('tingkat', models.CharField(help_text='Nasional/Internasional', max_length=50)),
                ('link_sertifikat', models.URLField(blank=True, null=True, verbose_name='Link Foto/Sertifikat')),
                ('status', models.CharField(choices=[('pending', 'Menunggu Review'), ('approved', 'Disetujui'), ('rejected', 'Ditolak')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
