# Generated by Django 6.0.1 on 2026-01-25 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoLomba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('penyelenggara', models.CharField(max_length=100)),
                ('tanggal_pelaksanaan', models.DateField()),
                ('pamflet', models.ImageField(blank=True, null=True, upload_to='pamflet_lomba/')),
                ('deskripsi_lengkap', models.TextField(blank=True, null=True)),
                ('link_pendaftaran', models.URLField(blank=True, help_text='Link Google Form / Website Lomba', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
