# Generated by Django 6.0.1 on 2026-01-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materi', '0002_infolomba'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestasi',
            name='foto_diri',
            field=models.ImageField(blank=True, help_text='Upload foto terbaik (Formal/Bebas Sopan)', null=True, upload_to='foto_prestasi/'),
        ),
        migrations.AddField(
            model_name='prestasi',
            name='is_public',
            field=models.BooleanField(default=True, verbose_name='Bersedia Diposting?'),
        ),
        migrations.AddField(
            model_name='prestasi',
            name='jenis_lomba',
            field=models.CharField(choices=[('Sains', 'Sains & Teknologi'), ('Olahraga', 'Olahraga'), ('Seni', 'Seni & Budaya'), ('Lainnya', 'Lainnya')], default='Sains', max_length=20),
        ),
        migrations.AddField(
            model_name='prestasi',
            name='kategori',
            field=models.CharField(choices=[('Individu', 'Individu'), ('Kelompok', 'Kelompok/Tim')], default='Individu', max_length=20),
        ),
        migrations.AddField(
            model_name='prestasi',
            name='no_hp',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='No HP / WA'),
        ),
        migrations.AddField(
            model_name='prestasi',
            name='no_sk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='No. SK / Surat Tugas'),
        ),
        migrations.AddField(
            model_name='prestasi',
            name='penyelenggara',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestasi',
            name='tempat_tanggal',
            field=models.CharField(default=' ', help_text='Contoh: Semarang, 1-4 September 2025', max_length=200, verbose_name='Tempat & Tanggal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='prestasi',
            name='url_penyelenggara',
            field=models.URLField(blank=True, null=True, verbose_name='Website/Sosmed Penyelenggara'),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='juara',
            field=models.CharField(help_text='Contoh: Juara 1, Medali Emas, Best Speaker', max_length=100),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='link_sertifikat',
            field=models.URLField(default='-', help_text='Pastikan link Google Drive bersifat Public', verbose_name='Link Drive (Sertifikat & Foto Kegiatan)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='nama_mahasiswa',
            field=models.CharField(help_text='Format: Nama Lengkap (NIM)', max_length=200, verbose_name='Nama & NIM'),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='tingkat',
            field=models.CharField(choices=[('Internasional', 'Internasional'), ('Nasional', 'Nasional'), ('Provinsi', 'Provinsi'), ('Kota', 'Kota/Kabupaten'), ('Kampus', 'Internal Kampus')], default='Nasional', max_length=20),
        ),
    ]
