# Generated by Django 6.0.1 on 2026-01-25 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materi', '0003_prestasi_foto_diri_prestasi_is_public_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materi',
            name='link_materi',
        ),
        migrations.AddField(
            model_name='karya',
            name='gambar_cover',
            field=models.ImageField(blank=True, help_text='Screenshot/Foto Karya', null=True, upload_to='cover_karya/'),
        ),
        migrations.AddField(
            model_name='materi',
            name='file_materi',
            field=models.FileField(blank=True, help_text='Upload file PDF/PPT langsung ke server (Opsional)', null=True, upload_to='dokumen_materi/'),
        ),
        migrations.AddField(
            model_name='materi',
            name='link_google_drive',
            field=models.URLField(blank=True, help_text='Isi jika materi ada di Google Drive (Pastikan akses Public)', null=True),
        ),
    ]
