# Generated by Django 6.0.1 on 2026-01-27 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materi', '0004_remove_materi_link_materi_karya_gambar_cover_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infolomba',
            name='tanggal_buka_pendaftaran',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='infolomba',
            name='tanggal_tutup_pendaftaran',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infolomba',
            name='tanggal_pelaksanaan',
            field=models.DateField(help_text='Tanggal Lomba Dimulai'),
        ),
    ]
