# Generated by Django 6.0.1 on 2026-01-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materi', '0005_infolomba_tanggal_buka_pendaftaran_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='karya',
            name='link_demo',
        ),
        migrations.AddField(
            model_name='karya',
            name='link_video',
            field=models.URLField(blank=True, help_text="Paste link Google Drive Video Demo di sini (Pastikan akses 'Public')", null=True, verbose_name='Link Google Drive Video'),
        ),
        migrations.AlterField(
            model_name='karya',
            name='gambar_cover',
            field=models.ImageField(blank=True, help_text='Upload Foto Alat/Karya (Maksimal 2MB)', null=True, upload_to='cover_karya/'),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='foto_diri',
            field=models.ImageField(blank=True, help_text='Upload foto terbaik (Formal/Bebas Sopan). Maksimal 2MB.', null=True, upload_to='foto_prestasi/'),
        ),
    ]
