# Generated by Django 6.0.1 on 2026-01-27 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materi', '0006_remove_karya_link_demo_karya_link_video_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infolomba',
            name='pamflet',
        ),
        migrations.RemoveField(
            model_name='infolomba',
            name='tanggal_tutup_pendaftaran',
        ),
        migrations.AddField(
            model_name='infolomba',
            name='kategori',
            field=models.CharField(default='Nasional', help_text='Contoh: Nasional, Internasional, Internal', max_length=50),
        ),
        migrations.AddField(
            model_name='infolomba',
            name='poster',
            field=models.ImageField(blank=True, null=True, upload_to='poster_lomba/'),
        ),
        migrations.AddField(
            model_name='infolomba',
            name='tanggal_deadline',
            field=models.DateField(blank=True, help_text='Batas akhir pendaftaran', null=True),
        ),
    ]
