# Generated by Django 6.0.1 on 2026-01-27 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materi', '0007_remove_infolomba_pamflet_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infolomba',
            name='url_penyelenggara',
            field=models.URLField(blank=True, help_text='Link Website, Instagram, atau Guidebook Lomba (Untuk tombol More Info)', null=True, verbose_name='Link Info/Sosmed'),
        ),
        migrations.AlterField(
            model_name='infolomba',
            name='kategori',
            field=models.CharField(choices=[('Internasional', 'Internasional'), ('Nasional', 'Nasional'), ('Provinsi', 'Provinsi'), ('Kota', 'Kota/Kabupaten'), ('Kampus', 'Internal Kampus'), ('Umum', 'Umum')], default='Nasional', help_text='Pilih tingkatan lomba untuk label (Badge)', max_length=50),
        ),
        migrations.AlterField(
            model_name='infolomba',
            name='link_pendaftaran',
            field=models.URLField(blank=True, help_text='Link untuk mendaftar (Tombol Daftar)', null=True),
        ),
    ]
