# Generated by Django 6.0.1 on 2026-01-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materi', '0008_infolomba_url_penyelenggara_alter_infolomba_kategori_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaKalender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kegiatan', models.CharField(max_length=200)),
                ('tanggal_mulai', models.DateField()),
                ('tanggal_selesai', models.DateField(blank=True, null=True)),
                ('warna', models.CharField(choices=[('primary', 'Biru (Normal)'), ('success', 'Hijau (Penting)'), ('warning', 'Kuning (Warning)'), ('danger', 'Merah (Libur/Deadline)')], default='primary', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FileKalender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_file', models.CharField(default='Kalender Akademik PDF', max_length=100)),
                ('file_pdf', models.FileField(help_text='Upload PDF Kalender Akademik Resmi di sini', upload_to='dokumen_kalender/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
