# Generated by Django 6.0.1 on 2026-01-28 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materi', '0009_agendakalender_filekalender'),
    ]

    operations = [
        migrations.AddField(
            model_name='materi',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover_materi/', verbose_name='Cover Materi'),
        ),
        migrations.AddField(
            model_name='materi',
            name='dosen',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Dosen Pengampu'),
        ),
        migrations.AddField(
            model_name='prestasi',
            name='nim',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='NIM'),
        ),
        migrations.AlterField(
            model_name='infolomba',
            name='kategori',
            field=models.CharField(choices=[('Internasional', 'Internasional'), ('Nasional', 'Nasional'), ('Provinsi', 'Provinsi'), ('Kota', 'Kota/Kabupaten'), ('Kampus', 'Internal Kampus'), ('Umum', 'Umum')], default='Nasional', help_text='Pilih tingkatan lomba', max_length=50),
        ),
        migrations.AlterField(
            model_name='infolomba',
            name='link_pendaftaran',
            field=models.URLField(blank=True, help_text='Link Google Form / Web Pendaftaran', null=True),
        ),
        migrations.AlterField(
            model_name='infolomba',
            name='tanggal_pelaksanaan',
            field=models.DateField(blank=True, help_text='Tanggal Lomba Dimulai', null=True),
        ),
        migrations.AlterField(
            model_name='infolomba',
            name='url_penyelenggara',
            field=models.URLField(blank=True, help_text='Link Website, Instagram, atau Guidebook Lomba', null=True, verbose_name='Link Info/Sosmed'),
        ),
        migrations.AlterField(
            model_name='karya',
            name='link_video',
            field=models.URLField(blank=True, help_text='Paste link Google Drive / YouTube Video Demo di sini', null=True, verbose_name='Link Video'),
        ),
        migrations.AlterField(
            model_name='materi',
            name='email',
            field=models.EmailField(blank=True, help_text='Email untuk notifikasi jika materi diterima/ditolak', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='juara',
            field=models.CharField(help_text='Contoh: Juara 1, Medali Emas', max_length=100),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='link_sertifikat',
            field=models.URLField(help_text='Pastikan link Google Drive bersifat Public', verbose_name='Link Drive Sertifikat'),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='nama_mahasiswa',
            field=models.CharField(max_length=200, verbose_name='Nama Lengkap'),
        ),
    ]
