# Generated by Django 6.0.1 on 2026-01-29 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materi', '0010_materi_cover_materi_dosen_prestasi_nim_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filekalender',
            name='file_pdf',
            field=models.FileField(upload_to='dokumen_kalender/'),
        ),
        migrations.AlterField(
            model_name='infolomba',
            name='kategori',
            field=models.CharField(choices=[('Internasional', 'Internasional'), ('Nasional', 'Nasional'), ('Provinsi', 'Provinsi'), ('Kota', 'Kota/Kabupaten'), ('Kampus', 'Internal Kampus'), ('Umum', 'Umum')], default='Nasional', max_length=50),
        ),
        migrations.AlterField(
            model_name='infolomba',
            name='link_pendaftaran',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infolomba',
            name='tanggal_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infolomba',
            name='tanggal_pelaksanaan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='infolomba',
            name='url_penyelenggara',
            field=models.URLField(blank=True, null=True, verbose_name='Link Info/Sosmed'),
        ),
        migrations.AlterField(
            model_name='karya',
            name='gambar_cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover_karya/'),
        ),
        migrations.AlterField(
            model_name='karya',
            name='link_video',
            field=models.URLField(blank=True, null=True, verbose_name='Link Video'),
        ),
        migrations.AlterField(
            model_name='materi',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='materi',
            name='file_materi',
            field=models.FileField(blank=True, null=True, upload_to='dokumen_materi/'),
        ),
        migrations.AlterField(
            model_name='materi',
            name='link_google_drive',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='foto_diri',
            field=models.ImageField(blank=True, null=True, upload_to='foto_prestasi/'),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='juara',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='link_sertifikat',
            field=models.URLField(verbose_name='Link Drive Sertifikat'),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='tempat_tanggal',
            field=models.CharField(max_length=200, verbose_name='Tempat & Tanggal'),
        ),
    ]
