# Generated by Django 6.0.1 on 2026-02-06 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materi', '0011_alter_filekalender_file_pdf_alter_infolomba_kategori_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgendaAkademik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kegiatan', models.CharField(max_length=255)),
                ('tanggal_mulai', models.DateField()),
                ('warna', models.CharField(choices=[('primary', 'Biru'), ('danger', 'Merah'), ('warning', 'Kuning'), ('success', 'Hijau')], default='primary', max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Agenda Akademik',
            },
        ),
        migrations.DeleteModel(
            name='AgendaKalender',
        ),
        migrations.DeleteModel(
            name='FileKalender',
        ),
        migrations.AlterModelOptions(
            name='infolomba',
            options={'verbose_name_plural': 'Info Lomba'},
        ),
        migrations.AlterModelOptions(
            name='karya',
            options={'verbose_name_plural': 'Karya'},
        ),
        migrations.AlterModelOptions(
            name='materi',
            options={'verbose_name_plural': 'Materi'},
        ),
        migrations.AlterModelOptions(
            name='prestasi',
            options={'verbose_name_plural': 'Prestasi'},
        ),
        migrations.RemoveField(
            model_name='infolomba',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='infolomba',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='infolomba',
            name='link_pendaftaran',
        ),
        migrations.RemoveField(
            model_name='infolomba',
            name='poster',
        ),
        migrations.RemoveField(
            model_name='infolomba',
            name='tanggal_buka_pendaftaran',
        ),
        migrations.RemoveField(
            model_name='infolomba',
            name='tanggal_deadline',
        ),
        migrations.RemoveField(
            model_name='infolomba',
            name='url_penyelenggara',
        ),
        migrations.RemoveField(
            model_name='karya',
            name='deskripsi',
        ),
        migrations.RemoveField(
            model_name='karya',
            name='gambar_cover',
        ),
        migrations.RemoveField(
            model_name='karya',
            name='link_video',
        ),
        migrations.RemoveField(
            model_name='materi',
            name='cover',
        ),
        migrations.RemoveField(
            model_name='materi',
            name='deskripsi',
        ),
        migrations.RemoveField(
            model_name='materi',
            name='dosen',
        ),
        migrations.RemoveField(
            model_name='materi',
            name='email',
        ),
        migrations.RemoveField(
            model_name='materi',
            name='file_materi',
        ),
        migrations.RemoveField(
            model_name='materi',
            name='nama_pengupload',
        ),
        migrations.RemoveField(
            model_name='materi',
            name='status',
        ),
        migrations.RemoveField(
            model_name='prestasi',
            name='is_public',
        ),
        migrations.RemoveField(
            model_name='prestasi',
            name='jenis_lomba',
        ),
        migrations.RemoveField(
            model_name='prestasi',
            name='juara',
        ),
        migrations.RemoveField(
            model_name='prestasi',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='prestasi',
            name='link_sertifikat',
        ),
        migrations.RemoveField(
            model_name='prestasi',
            name='nim',
        ),
        migrations.RemoveField(
            model_name='prestasi',
            name='no_hp',
        ),
        migrations.RemoveField(
            model_name='prestasi',
            name='no_sk',
        ),
        migrations.RemoveField(
            model_name='prestasi',
            name='penyelenggara',
        ),
        migrations.RemoveField(
            model_name='prestasi',
            name='tempat_tanggal',
        ),
        migrations.RemoveField(
            model_name='prestasi',
            name='tingkat',
        ),
        migrations.RemoveField(
            model_name='prestasi',
            name='url_penyelenggara',
        ),
        migrations.AlterField(
            model_name='infolomba',
            name='judul',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='infolomba',
            name='penyelenggara',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='karya',
            name='judul_karya',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='karya',
            name='pembuat',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='karya',
            name='prodi',
            field=models.CharField(choices=[('PTIK', 'Pendidikan TIK'), ('PTE', 'Pendidikan Teknik Elektro'), ('TE', 'Teknik Elektro'), ('TK', 'TEKKOM'), ('MKU', 'Mata Kuliah Umum')], default='PTIK', max_length=10),
        ),
        migrations.AlterField(
            model_name='karya',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ Pending'), ('approved', '✅ Approved'), ('rejected', '❌ Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='materi',
            name='judul',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='materi',
            name='link_google_drive',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='materi',
            name='mata_kuliah',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='materi',
            name='prodi',
            field=models.CharField(choices=[('PTIK', 'Pendidikan TIK'), ('PTE', 'Pendidikan Teknik Elektro'), ('TE', 'Teknik Elektro'), ('TK', 'TEKKOM'), ('MKU', 'Mata Kuliah Umum')], max_length=10),
        ),
        migrations.AlterField(
            model_name='materi',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='foto_diri',
            field=models.ImageField(blank=True, null=True, upload_to='prestasi/'),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='nama_lomba',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='nama_mahasiswa',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='prodi',
            field=models.CharField(choices=[('PTIK', 'Pendidikan TIK'), ('PTE', 'Pendidikan Teknik Elektro'), ('TE', 'Teknik Elektro'), ('TK', 'TEKKOM'), ('MKU', 'Mata Kuliah Umum')], max_length=10),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='status',
            field=models.CharField(choices=[('pending', '⏳ Pending'), ('approved', '✅ Approved'), ('rejected', '❌ Rejected')], default='pending', max_length=20),
        ),
    ]
