# Generated by Django 6.0.1 on 2026-02-06 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materi', '0012_agendaakademik_delete_agendakalender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KalenderPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_file', models.CharField(default='Kalender Akademik', max_length=255)),
                ('link_google_drive', models.URLField(help_text='Masukkan link PDF dari Google Drive', max_length=500)),
                ('tanggal_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'File Kalender PDF',
            },
        ),
    ]
