# Generated by Django 6.0.1 on 2026-02-06 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materi', '0013_kalenderpdf'),
    ]

    operations = [
        migrations.RenameField(
            model_name='infolomba',
            old_name='deskripsi_lengkap',
            new_name='deskripsi',
        ),
        migrations.RemoveField(
            model_name='prestasi',
            name='foto_diri',
        ),
        migrations.AddField(
            model_name='infolomba',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='infolomba',
            name='kategori',
            field=models.CharField(default='UMUM', help_text='Contoh: Robotik, Web Design, dll', max_length=100),
        ),
        migrations.AddField(
            model_name='infolomba',
            name='link_pendaftaran',
            field=models.URLField(blank=True, help_text='Link formulir pendaftaran', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='infolomba',
            name='link_poster',
            field=models.URLField(blank=True, help_text='Link poster dari Google Drive/Imgur', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='infolomba',
            name='tanggal_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prestasi',
            name='link_foto',
            field=models.URLField(blank=True, help_text='Link foto dari Google Drive/Cloud', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='karya',
            name='prodi',
            field=models.CharField(choices=[('PTIK', 'PTIK'), ('PTE', 'PTE'), ('TE', 'TE'), ('TK', 'TEKKOM'), ('MKU', 'MKU')], default='PTIK', max_length=10),
        ),
        migrations.AlterField(
            model_name='materi',
            name='prodi',
            field=models.CharField(choices=[('PTIK', 'PTIK'), ('PTE', 'PTE'), ('TE', 'TE'), ('TK', 'TEKKOM'), ('MKU', 'MKU')], max_length=10),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='prodi',
            field=models.CharField(choices=[('PTIK', 'PTIK'), ('PTE', 'PTE'), ('TE', 'TE'), ('TK', 'TEKKOM'), ('MKU', 'MKU')], max_length=10),
        ),
    ]
