# Generated by Django 6.0.1 on 2026-02-06 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materi', '0014_rename_deskripsi_lengkap_infolomba_deskripsi_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendaakademik',
            options={},
        ),
        migrations.AlterModelOptions(
            name='kalenderpdf',
            options={},
        ),
        migrations.RemoveField(
            model_name='infolomba',
            name='link_poster',
        ),
        migrations.AddField(
            model_name='infolomba',
            name='link_booklet',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='infolomba',
            name='link_sosmed',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='infolomba',
            name='kategori',
            field=models.CharField(default='UMUM', max_length=100),
        ),
        migrations.AlterField(
            model_name='infolomba',
            name='link_pendaftaran',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='kalenderpdf',
            name='link_google_drive',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='link_foto',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
