# Generated by Django 6.0.1 on 2026-02-06 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materi', '0015_alter_agendaakademik_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infolomba',
            name='link_poster',
            field=models.URLField(blank=True, help_text='Link poster dari Google Drive/Imgur', max_length=500, null=True),
        ),
    ]
