# Generated by Django 6.0.1 on 2026-02-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materi', '0016_infolomba_link_poster'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendaakademik',
            options={'ordering': ['tanggal_mulai'], 'verbose_name_plural': 'Agenda Akademik'},
        ),
        migrations.AddField(
            model_name='agendaakademik',
            name='tanggal_selesai',
            field=models.DateField(blank=True, help_text='Kosongkan jika hanya satu hari', null=True),
        ),
        migrations.AlterField(
            model_name='agendaakademik',
            name='warna',
            field=models.CharField(choices=[('primary', 'Biru (Umum)'), ('danger', 'Merah (Penting)'), ('warning', 'Kuning (Pengingat)'), ('success', 'Hijau (Opsional)')], default='primary', max_length=10),
        ),
    ]
