# Generated by Django 6.0.1 on 2026-02-10 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materi', '0017_alter_agendaakademik_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karya',
            name='prodi',
            field=models.CharField(choices=[('PTIK', 'PTIK'), ('PTE', 'PTE'), ('TE', 'TE'), ('TEKKOM', 'TEKKOM'), ('MKU', 'MKU')], default='PTIK', max_length=10),
        ),
        migrations.AlterField(
            model_name='materi',
            name='prodi',
            field=models.CharField(choices=[('PTIK', 'PTIK'), ('PTE', 'PTE'), ('TE', 'TE'), ('TEKKOM', 'TEKKOM'), ('MKU', 'MKU')], max_length=10),
        ),
        migrations.AlterField(
            model_name='prestasi',
            name='prodi',
            field=models.CharField(choices=[('PTIK', 'PTIK'), ('PTE', 'PTE'), ('TE', 'TE'), ('TEKKOM', 'TEKKOM'), ('MKU', 'MKU')], max_length=10),
        ),
    ]
